version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    entrypoint: ./wsgi-entrypoint.sh
    volumes:
      - ./media/:/media/
      - ./static/:/static/
      - ./staticfiles/:/staticfiles/
      - ./sql-data/:/db.sqlite3
      - ./:/app
    networks:
      - stac
    env_file:
       - .env

networks:
  stac:

volumes:
  media:
  static:
  staticfiles:
  sql-data: